### ISSUE TITLE
The `hasMany` relationship doesn't rely on primaryKey

### ISSUE THREAD

**Issue by paparent** [vuex-orm/vuex-orm#53]
Hi,

The `hasMany` relies on `id` instead of the configurable `primaryKey`. Should be using the custom value :)

https://github.com/vuex-orm/vuex-orm/blob/master/src/repo/Repo.ts#L655

(I'll try to fix it.. dunno if hard).

**Comment by kiaking** [comment]
Thank you for the report! I just fixed this issue few seconds ago 😅 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.16.1

Thank you for finding out this bug though! It was so easy miss. Also, we should add feature to have custom local key too (it is another issue but.

```js
class User extends Model {
  static fields () {
    id: this.attr(null),
    id_for_post: this.attr(null),
    posts: this.hasMany(Post, 'user_id', 'id_for_post') // The 3rd arg is the local key to reference. Defaults to `id`.
  }
}
```

**Comment by paparent** [comment]
Thanks a lot ! Works like a charm now 🥇

**Comment by kiaking** [comment]
Glad I could help 🎉  Feel free to raise issue if you need anything else 🚀

**Comment by tjsteinhaus** [comment]
@kiaking Does this work for hasOne as well?

**Comment by kiaking** [comment]
@tjsteinhaus Yes it does. I've fixed both `hasOne` and `hasMany` 😃

**Comment by tjsteinhaus** [comment]
Can you identify what the issue is with my models then? It doesn't appear to be working and I'm on the most recent version of Vuex ORM.

```import { Model } from '@vuex-orm/core'

import AssessorsIndex from './AssessorsIndex';
import Evaluations from './Evaluations';


export default class Assessors extends Model {
	static entity = 'assessors'

	static fields () {
		return {
			id: this.attr(null),
			assessorIndexId: this.attr(null),
			info: this.hasOne(AssessorsIndex, 'id', 'assessorIndexId'),
			evaluationId: this.hasOne(Evaluations, 'evaluationId'),
			meta_data: this.attr(null),
			order: this.attr(null),
			created_at: this.attr(null),
			updated_at: this.attr(null),
			deleted_at: this.attr(null)
		}
	}

	static mutators () {
		return {

		}
	}
}
```

```import { Model } from '@vuex-orm/core';

import Assessors from './Assessors';

export default class AssessorsIndex extends Model {
  static entity = 'assessorsindex'

  static fields () {
    return {
      id: this.attr(null),
      name: this.attr(''),
      enabled: this.attr(''),
	 assessors: this.belongsTo( Assessors, 'id', 'assessorIndexId' )
    }
  }
}
```

Both Assessors attribute 'info' and AssessorsIndex attribute 'assessors' are returning null.

**Comment by kiaking** [comment]
OK the correct way of defining this two relationship is as follow.

```js
import AssessorsIndex from './AssessorsIndex'
import Evaluations from './Evaluations'

export default class Assessors extends Model {
  static entity = 'assessors'

  static fields () {
    return {
      id: this.attr(null),
      assessorIndexId: this.attr(null),
      info: this.belongsTo(AssessorsIndex, 'assessorIndexId'), // <- Should be belongsTo.
      evaluationId: this.belongsTo(Evaluations, 'evaluationId'), // <- I think this also should be belongsTo.
      meta_data: this.attr(null),
      order: this.attr(null),
      created_at: this.attr(null),
      updated_at: this.attr(null),
      deleted_at: this.attr(null)
    }
  }
}
```

```js
import Assessors from './Assessors'

export default class AssessorsIndex extends Model {
  static entity = 'assessorsindex'

  static fields () {
    return {
      id: this.attr(null),
      name: this.attr(''),
      enabled: this.attr(''),
      assessors: this.hasOne(Assessors, 'assessorIndexId') // <- Should be hasOne.
    }
  }
}
```

Basically, if the model it self has the foreign key, then that model "belongs to" other model. Since Assessors has foreign key of `assessorIndexId`, then Assessors belongs to AssessorsIndex, and AssessorsIndex "has one" Assessors.

**Comment by tjsteinhaus** [comment]
It's still not working that way either. Basically AssessorsIndex is just a list of different types of Assessors and the Assessors is a list of all the assessors in an evaluations. So there will be a lot of assessors and the assessorIndexId only hasOne index from the AssessorsIndex. 

In the Laravel backend 'info' basically returns the data from that row in the AssessorsIndex. 

I'm trying to replicate my Laravel Database/API for my Vue application as it will need to be offline and I'm really hoping Vuex-ORM can do the trick for this. (not the offline, just the db structure)

**Comment by kiaking** [comment]
Strange. To farther investigate, I need to know the response JSON from Laravel and how your are storing that data into Vuex ORM. Is it possible for you to send me the actual code? (if it's ok with you, email me at kia.king.08@gmail.com). Also maybe database schema from Laravel migration file could be helpful too.

With your models, my imagination is you have these kind of workflow.

```js
// Assume this is the response from Laravel. You are fetching Assessors.
const data = {
  id: 1,
  assessorsIndexId: 3,
  info: {
    id: 3,
    name: 'some name',
    enabled: true
  },
  evaluationId: 10,
  meta_data: ...
  // and so on
}

// When you save above data.
store.dispatch('entities/assessors/create', { data })

// Inside Vuex Store becomes like this.
{
  entities: {
    assessors: {
      data: {
        '1': {
          id: 1,
          assessorsIndexId: 3,
          info: 3,
          evaluationId: 10,
          meta_data: ...
          // and so on
        }
      }
    },
    assessorsIndex: {
      data: {
        '3': {
          id: 3,
          name: 'some name',
          enabled: true
        }
      }
    }
  }
}

// Then you can fetch including relations.
store.getters['entities/assessors/query']().with('assessorsIndex').get()

// The result will be
{
  id: 1,
  assessorsIndexId: 3,
  info: {
    id: 3,
    name: 'some name',
    enabled: true
  },
  evaluationId: 10,
  meta_data: ...
}
```

> I'm trying to replicate my Laravel Database/API for my Vue application as it will need to be offline and I'm really hoping Vuex-ORM can do the trick for this. (not the offline, just the db structure)

Yes it should be! I'm using Vuex ORM with Laravel and just replicating it.

**Comment by tjsteinhaus** [comment]
I just figured out what the issue was. I'm trying to call more than one relationship under a relationship. See code below:

```this.$store.getters['entities/evaluations/query']()
				.with( 'groups.assessors' )
				.with( 'assessors.info' )
				.with( 'assessors.group' )
				.get()
```

If I take out `.with( 'assessors.group' )` it displays all the data that should be under the relationship for 'info'. If I add back in `.with( 'assessors.group' )` it displays the data that should be under the relationship for 'group' but not 'info'. Is there a way to get another added without this issue? If I try and chain like so `.with( 'assessors.info.group' )` it only shows the data for `info`.

**Comment by kiaking** [comment]
Ah OK. If you want add more than one nested relation, you need to use closure.

```js
store.getters['entities/evaluations/query']()
  .with('assessors', (query) => {
    query.with('info').with('group')
  })
  .with('groups.assessors')
  .get()
```

Could you try the above code?
